const names = [
    "Precious Achiuwa",
    "Steven Adams",
    "Bam Adebayo",
    "Default player headshot",
    "Santi Aldama",
    "LaMarcus Aldridge",
    "Nickeil Alexander-Walker",
    "Grayson Allen",
    "Jarrett Allen",
    "Jose Alvarado",
    "Kyle Anderson",
    "Giannis Antetokounmpo",
    "Thanasis Antetokounmpo",
    "Carmelo Anthony",
    "Cole Anthony",
    "OG Anunoby",
    "Default player headshot",
    "D.J. Augustin",
    "Deni Avdija",
    "Deandre Ayton",
    "Udoka Azubuike",
    "Marvin Bagley III",
    "Default player headshot",
    "LaMelo Ball",
    "Lonzo Ball",
    "Mo Bamba",
    "Default player headshot",
    "Desmond Bane",
    "Dalano Banton",
    "Default player headshot",
    "Harrison Barnes",
    "Scottie Barnes",
    "RJ Barrett",
    "Will Barton",
    "Charles Bassey",
    "Keita Bates-Diop",
    "Nicolas Batum",
    "Kent Bazemore",
    "Darius Bazley",
    "Bradley Beal",
    "Malik Beasley",
    "Default player headshot",
    "Davis Bertans",
    "Default player headshot",
    "Patrick Beverley",
    "Saddiq Bey",
    "Khem Birch",
    "Goga Bitadze",
    "Bismack Biyombo",
    "Nemanja Bjelica",
    "Keljin Blevins",
    "Default player headshot",
    "Bogdan Bogdanovic",
    "Bojan Bogdanovic",
    "Bol Bol",
    "Leandro Bolmaro",
    "Isaac Bonga",
    "Devin Booker",
    "Brandon Boston",
    "Chris Boucher",
    "James Bouknight",
    "Default player headshot",
    "Avery Bradley",
    "Tony Bradley",
    "Malaki Branham",
    "Christian Braun",
    "Ignas Brazdeikis",
    "Mikal Bridges",
    "Miles Bridges",
    "Oshae Brissett",
    "Malcolm Brogdon",
    "Dillon Brooks",
    "Bruce Brown",
    "Jaylen Brown",
    "Kendall Brown",
    "Moses Brown",
    "Sterling Brown",
    "Greg Brown III",
    "Charlie Brown Jr.",
    "Chaundee Brown Jr.",
    "Troy Brown Jr.",
    "Jalen Brunson",
    "Thomas Bryant",
    "Reggie Bullock",
    "Trey Burke",
    "Alec Burks",
    "Jared Butler",
    "Jimmy Butler",
    "Devontae Cacok",
    "Jamal Cain",
    "Kentavious Caldwell-Pope",
    "Facundo Campazzo",
    "Vlatko Cancar",
    "Devin Cannady",
    "Clint Capela",
    "Vernon Carey Jr.",
    "Jevon Carter",
    "Wendell Carter Jr.",
    "Alex Caruso",
    "Julian Champagnie",
    "Justin Champagnie",
    "Default player headshot",
    "Chris Chiozza",
    "Marquese Chriss",
    "Default player headshot",
    "Josh Christopher",
    "Gary Clark",
    "Brandon Clarke",
    "Jordan Clarkson",
    "Nic Claxton",
    "Amir Coffey",
    "John Collins",
    "Zach Collins",
    "Mike Conley",
    "Pat Connaughton",
    "Tyler Cook",
    "DeMarcus Cousins",
    "Robert Covington",
    "Torrey Craig",
    "Jae Crowder",
    "Jarrett Culver",
    "Cade Cunningham",
    "Seth Curry",
    "Stephen Curry",
    "Dyson Daniels",
    "Anthony Davis",
    "Ed Davis",
    "Johnny Davis",
    "Terence Davis",
    "JD Davison",
    "Darius Days",
    "DeMar DeRozan",
    "Dewayne Dedmon",
    "Matthew Dellavedova",
    "Donte DiVincenzo",
    "Moussa Diabate",
    "Hamidou Diallo",
    "Gorgui Dieng",
    "Ousmane Dieng",
    "Spencer Dinwiddie",
    "Khalifa Diop",
    "Luka Doncic",
    "Tyler Dorsey",
    "Luguentz Dort",
    "Ayo Dosunmu",
    "Jeff Dowtin",
    "Goran Dragic",
    "Andre Drummond",
    "Chris Duarte",
    "David Duke Jr.",
    "Kevin Durant",
    "Default player headshot",
    "Default player headshot",
    "Anthony Edwards",
    "Kessler Edwards",
    "CJ Elleby",
    "Wayne Ellington",
    "Default player headshot",
    "Joel Embiid",
    "Drew Eubanks",
    "Derrick Favors",
    "Bruno Fernando",
    "Dorian Finney-Smith",
    "Malachi Flynn",
    "Simone Fontecchio",
    "Bryn Forbes",
    "Trent Forrest",
    "Michael Foster Jr.",
    "Evan Fournier",
    "De'Aaron Fox",
    "Javon Freeman-Liberty",
    "Markelle Fultz",
    "Wenyen Gabriel",
    "Daniel Gafford",
    "Danilo Gallinari",
    "Darius Garland",
    "Marcus Garrett",
    "Usman Garuba",
    "Luka Garza",
    "Rudy Gay",
    "Paul George",
    "Taj Gibson",
    "Josh Giddey",
    "Shai Gilgeous-Alexander",
    "Anthony Gill",
    "Collin Gillespie",
    "Rudy Gobert",
    "Brandon Goodwin",
    "Aaron Gordon",
    "Eric Gordon",
    "Kellan Grady",
    "Devonte' Graham",
    "Jerami Grant",
    "A.J. Green",
    "Danny Green",
    "Draymond Green",
    "JaMychal Green",
    "Jalen Green",
    "Javonte Green",
    "Jeff Green",
    "Josh Green",
    "Default player headshot",
    "Blake Griffin",
    "Quentin Grimes",
    "Rui Hachimura",
    "Tyrese Haliburton",
    "R.J. Hampton",
    "Tim Hardaway Jr.",
    "James Harden",
    "Default player headshot",
    "Maurice Harkless",
    "Jared Harper",
    "Default player headshot",
    "Montrezl Harrell",
    "Gary Harris",
    "Joe Harris",
    "Kevon Harris",
    "Tobias Harris",
    "Josh Hart",
    "Isaiah Hartenstein",
    "Udonis Haslem",
    "Sam Hauser",
    "Jaxson Hayes",
    "Killian Hayes",
    "Gordon Hayward",
    "Juancho Hernangomez",
    "Willy Hernangomez",
    "Tyler Herro",
    "Buddy Hield",
    "Haywood Highsmith",
    "George Hill",
    "Malcolm Hill",
    "Aaron Holiday",
    "Jrue Holiday",
    "Justin Holiday",
    "Richaun Holmes",
    "Chet Holmgren",
    "Rodney Hood",
    "Al Horford",
    "Talen Horton-Tucker",
    "Danuel House Jr.",
    "Caleb Houstan",
    "Dwight Howard",
    "Markus Howard",
    "Trevor Hudgins",
    "Kevin Huerter",
    "Jay Huff",
    "Elijah Hughes",
    "Feron Hunt",
    "De'Andre Hunter",
    "Bones Hyland",
    "Serge Ibaka",
    "Andre Iguodala",
    "Joe Ingles",
    "Brandon Ingram",
    "Kyrie Irving",
    "Jonathan Isaac",
    "Default player headshot",
    "Frank Jackson",
    "Isaiah Jackson",
    "Josh Jackson",
    "Reggie Jackson",
    "Jaren Jackson Jr.",
    "LeBron James",
    "Ty Jerome",
    "Isaiah Joe",
    "Cameron Johnson",
    "David Johnson",
    "Jalen Johnson",
    "Keldon Johnson",
    "Keon Johnson",
    "Stanley Johnson",
    "Nikola Jokic",
    "Damian Jones",
    "Herbert Jones",
    "Kai Jones",
    "Tre Jones",
    "Tyus Jones",
    "Derrick Jones Jr.",
    "DeAndre Jordan",
    "Cory Joseph",
    "Nikola Jovic",
    "Johnny Juzang",
    "Mfiondu Kabengele",
    "Ismael Kamagate",
    "Frank Kaminsky",
    "Trevor Keels",
    "Luke Kennard",
    "Walker Kessler",
    "Braxton Key",
    "Corey Kispert",
    "Maxi Kleber",
    "Nathan Knight",
    "Kevin Knox II",
    "Christian Koloko",
    "John Konchar",
    "Furkan Korkmaz",
    "Luke Kornet",
    "Vit Krejci",
    "Arnoldas Kulboka",
    "Jonathan Kuminga",
    "Kyle Kuzma",
    "Default player headshot",
    "Zach LaVine",
    "Anthony Lamb",
    "Jeremy Lamb",
    "Jock Landale",
    "Romeo Langford",
    "A.J. Lawson",
    "Jake Layman",
    "Caris LeVert",
    "Damion Lee",
    "Saben Lee",
    "Alex Len",
    "Kawhi Leonard",
    "Justin Lewis",
    "Scottie Lewis",
    "Kira Lewis Jr.",
    "E.J. Liddell",
    "Damian Lillard",
    "Nassir Little",
    "Isaiah Livers",
    "Kenneth Lofton Jr.",
    "Kevon Looney",
    "Brook Lopez",
    "Robin Lopez",
    "Didi Louzada",
    "Kevin Love",
    "Kyle Lowry",
    "Gabriel Lundberg",
    "Timothe Luwawu-Cabarrot",
    "Trey Lyles",
    "Theo Maledon",
    "Sandro Mamukelashvili",
    "Terance Mann",
    "Tre Mann",
    "Boban Marjanovic",
    "Lauri Markkanen",
    "Naji Marshall",
    "Caleb Martin",
    "Cody Martin",
    "Tyrese Martin",
    "Kenyon Martin Jr.",
    "Garrison Mathews",
    "Bennedict Mathurin",
    "Karlo Matkovic",
    "Wesley Matthews",
    "Tyrese Maxey",
    "Skylar Mays",
    "Miles McBride",
    "Mac McClung",
    "CJ McCollum",
    "T.J. McConnell",
    "Default player headshot",
    "Jaden McDaniels",
    "Jalen McDaniels",
    "Doug McDermott",
    "JaVale McGee",
    "Default player headshot",
    "Rodney McGruder",
    "Jordan McLaughlin",
    "Ben McLemore",
    "De'Anthony Melton",
    "Chimezie Metu",
    "Khris Middleton",
    "Patty Mills",
    "Paul Millsap",
    "Shake Milton",
    "Josh Minott",
    "Davion Mitchell",
    "Donovan Mitchell",
    "Evan Mobley",
    "Isaiah Mobley",
    "Chima Moneke",
    "Malik Monk",
    "Greg Monroe",
    "Moses Moody",
    "Xavier Moon",
    "Wendell Moore Jr.",
    "Ja Morant",
    "Markieff Morris",
    "Monte Morris",
    "Marcus Morris Sr.",
    "Trey Murphy III",
    "Dejounte Murray",
    "Jamal Murray",
    "Keegan Murray",
    "Mike Muscala",
    "Svi Mykhailiuk",
    "Larry Nance Jr.",
    "Andrew Nembhard",
    "RJ Nembhard Jr.",
    "Aaron Nesmith",
    "Raul Neto",
    "Georges Niang",
    "Daishen Nix",
    "Zeke Nnaji",
    "Nerlens Noel",
    "Jaylen Nowell",
    "Frank Ntilikina",
    "Kendrick Nunn",
    "Jusuf Nurkic",
    "David Nwaba",
    "Jordan Nwora",
    "Default player headshot",
    "Royce O'Neale",
    "Chuma Okeke",
    "Josh Okogie",
    "Onyeka Okongwu",
    "Isaac Okoro",
    "Victor Oladipo",
    "Kelly Olynyk",
    "Eugene Omoruyi",
    "Cedi Osman",
    "Kelly Oubre Jr.",
    "Eric Paschall",
    "Chris Paul",
    "Cameron Payne",
    "Elfrid Payton",
    "Gary Payton II",
    "Jamorko Pickett",
    "Theo Pinson",
    "Scotty Pippen Jr.",
    "Mason Plumlee",
    "Jakob Poeltl",
    "Alekesej Pokusevski",
    "Yves Pons",
    "Jordan Poole",
    "Kevin Porter Jr.",
    "Michael Porter Jr.",
    "Otto Porter Jr.",
    "Bobby Portis",
    "Kristaps Porzingis",
    "Dwight Powell",
    "Myles Powell",
    "Norman Powell",
    "Jason Preston",
    "Joshua Primo",
    "Taurean Prince",
    "Payton Pritchard",
    "Gabriele Procida",
    "Trevelin Queen",
    "Neemias Queta",
    "Immanuel Quickley",
    "Lester Quinones",
    "Julius Randle",
    "Austin Reaves",
    "Cam Reddish",
    "Davon Reed",
    "Paul Reed",
    "Naz Reid",
    "Nick Richards",
    "Josh Richardson",
    "Austin Rivers",
    "Duncan Robinson",
    "Mitchell Robinson",
    "Default player headshot",
    "Jeremiah Robinson-Earl",
    "Isaiah Roby",
    "Default player headshot",
    "Default player headshot",
    "Derrick Rose",
    "Terrence Ross",
    "Terry Rozier",
    "Ricky Rubio",
    "D'Angelo Russell",
    "Matt Ryan",
    "Domantas Sabonis",
    "Gui Santos",
    "Dario Saric",
    "Jordan Schakel",
    "Admiral Schofield",
    "Dennis Schroder",
    "Alperen Sengun",
    "Collin Sexton",
    "Landry Shamet",
    "Day'Ron Sharpe",
    "Shaedon Sharpe",
    "Pascal Siakam",
    "Ben Simmons",
    "Marko Simonovic",
    "Anfernee Simons",
    "Jericho Sims",
    "Marcus Smart",
    "Ish Smith",
    "Jalen Smith",
    "Jabari Smith Jr.",
    "Xavier Sneed",
    "Tony Snell",
    "Jeremy Sochan",
    "Matteo Spagnolo",
    "Pat Spencer",
    "Jaden Springer",
    "Lamar Stevens",
    "DJ Stewart",
    "Isaiah Stewart",
    "Max Strus",
    "Jalen Suggs",
    "Edmond Sumner",
    "Cole Swider",
    "Jae'Sean Tate",
    "Jayson Tatum",
    "Terry Taylor",
    "Garrett Temple",
    "Default player headshot",
    "Daniel Theis",
    "Brodric Thomas",
    "Cam Thomas",
    "Isaiah Thomas",
    "Matt Thomas",
    "Klay Thompson",
    "Tristan Thompson",
    "JT Thor",
    "Matisse Thybulle",
    "Killian Tillie",
    "Xavier Tillman Sr.",
    "Isaiah Todd",
    "Obi Toppin",
    "Juan Toscano-Anderson",
    "Karl-Anthony Towns",
    "Luke Travers",
    "Gary Trent Jr.",
    "P.J. Tucker",
    "Rayjon Tucker",
    "Myles Turner",
    "Jonas Valanciunas",
    "Fred VanVleet",
    "Jarred Vanderbilt",
    "Devin Vassell",
    "Luca Vildoza",
    "Gabe Vincent",
    "Nikola Vucevic",
    "Dean Wade",
    "Franz Wagner",
    "Moritz Wagner",
    "Ish Wainright",
    "Jabari Walker",
    "Kemba Walker",
    "Lonnie Walker IV",
    "John Wall",
    "T.J. Warren",
    "P.J. Washington",
    "TyTy Washington Jr.",
    "Yuta Watanabe",
    "Lindy Waters III",
    "Trendon Watford",
    "Peyton Watson",
    "Quinndary Weatherspoon",
    "Blake Wesley",
    "Russell Westbrook",
    "Coby White",
    "Derrick White",
    "Default player headshot",
    "Default player headshot",
    "Hassan Whiteside",
    "Joe Wieskamp",
    "Aaron Wiggins",
    "Andrew Wiggins",
    "Lindell Wigginton",
    "Default player headshot",
    "Default player headshot",
    "Grant Williams",
    "Jalen Williams",
    "Jaylin Williams",
    "Kenrich Williams",
    "Lou Williams",
    "Mark Williams",
    "Patrick Williams",
    "Trevion Williams",
    "Ziaire Williams",
    "Robert Williams III",
    "Vince Williams Jr.",
    "Zion Williamson",
    "D.J. Wilson",
    "Dylan Windler",
    "Justise Winslow",
    "Cassius Winston",
    "James Wiseman",
    "Christian Wood",
    "Robert Woodard II",
    "Delon Wright",
    "Moses Wright",
    "McKinley Wright IV",
    "Thaddeus Young",
    "Trae Young",
    "Omer Yurtseven",
    "Ivica Zubac"
];

module.exports = names;